//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlanCart.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AlanCartEntities : DbContext
    {
        public AlanCartEntities()
            : base("name=AlanCartEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<UserData> UserData { get; set; }
        public DbSet<ProductData> ProductData { get; set; }
        public DbSet<CartOfUser> CartOfUser { get; set; }
        public DbSet<OrderData> OrderData { get; set; }
        public DbSet<OrderItem> OrderItem { get; set; }
    }
}
