//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlanCart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductData
    {
        public ProductData()
        {
            this.CartOfUser = new HashSet<CartOfUser>();
            this.OrderItem = new HashSet<OrderItem>();
        }
    
        public int Id { get; set; }
        public string Productname { get; set; }
        public int Price { get; set; }
        public int Stock { get; set; }
        public int Available { get; set; }
        public string ImgUrl { get; set; }
        public int SellerId { get; set; }
    
        public virtual ICollection<CartOfUser> CartOfUser { get; set; }
        public virtual ICollection<OrderItem> OrderItem { get; set; }
        public virtual UserData UserData { get; set; }
    }
}
