//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlanCart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserData
    {
        public UserData()
        {
            this.CartOfUser = new HashSet<CartOfUser>();
            this.OrderData = new HashSet<OrderData>();
            this.OrderData1 = new HashSet<OrderData>();
            this.ProductData = new HashSet<ProductData>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Nickname { get; set; }
        public int Role { get; set; }
    
        public virtual ICollection<CartOfUser> CartOfUser { get; set; }
        public virtual ICollection<OrderData> OrderData { get; set; }
        public virtual ICollection<OrderData> OrderData1 { get; set; }
        public virtual ICollection<ProductData> ProductData { get; set; }
    }
}
